# Generated by Django 3.0 on 2020-10-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
