# Generated by Django 3.0 on 2020-11-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201105_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pro_pic_student/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pro_pic_teacher/'),
        ),
    ]
