# Generated by Django 3.0 on 2020-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(null=True, upload_to='course_files/'),
        ),
    ]
