# Generated by Django 3.0 on 2020-11-07 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 13, 32, 998248, tzinfo=utc), verbose_name='expire_date'),
        ),
    ]
