# Generated by Django 3.0 on 2020-10-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_enrollment_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.Course'),
        ),
    ]
