# Generated by Django 3.0 on 2020-11-07 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201107_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 18, 54, 19, 902101, tzinfo=utc), verbose_name='expire_date'),
        ),
    ]
