# Generated by Django 3.0 on 2020-11-09 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201107_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='isIssued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='isValid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 14, 38, 34, 141963, tzinfo=utc), verbose_name='expire_date'),
        ),
    ]
