# Generated by Django 3.0 on 2020-11-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201030_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='name',
            new_name='enroll_key',
        ),
    ]
