# Generated by Django 3.0 on 2020-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201109_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(null=True, verbose_name='expire_date'),
        ),
    ]
