# Generated by Django 3.0 on 2020-11-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201102_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_key',
            field=models.CharField(default='Text here', max_length=100, null=True),
        ),
    ]
