# Generated by Django 3.0 on 2020-11-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_module_file'),
        ('course', '0006_auto_20201109_1600'),
    ]

    operations = [
    ]
