# Generated by Django 3.0 on 2020-11-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201024_0756'),
        ('course', '0007_auto_20201103_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
    ]
