# Generated by Django 3.0 on 2020-11-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20201103_0648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
