# Generated by Django 3.0 on 2020-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20201103_0703'),
        ('course', '0010_auto_20201103_0651'),
    ]

    operations = [
    ]
